passwd:
# Create "core" system-user and add vagrant insecure key to it
  users:
    - name: core
      ssh_authorized_keys:
        - "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key"

# Disable automatic updates, and reboot service
systemd:
  units:
    - name: update-engine.service
      mask: true
    - name: locksmithd.service
      mask: true

# Set SSL-certificates-path environment variable
# This fixes SSL errors in Python
storage:
  files:
    - path: /etc/profile.env
      filesystem: root
      mode: 0644
      contents:
        inline: |
          export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
